services:
  - type: worker
    name: forwardtest-live-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python forwardtest_v8_triple_live_two_symbols1.py"
    plan: free

